version: "3.9" # optional since v1.27.0
services:
  api:
    container_name: api-nodejs
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    networks:
      - compose-network
  client:
    container_name: client-nodejs
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:4000
    restart: unless-stopped
    networks:
      - compose-network
    depends_on:
      - api
    environment:
      - API_HOST=http://localhost:8080
networks:
  compose-network:
    name: simple-compose-network